export default {
  splash: "SPLASH",
  onboarding: "ONBOARDING",
  login: "LOGIN",
  signup: "SIGNUP",
  verify: "VERIFY",
  setpassword: "SETPASSWORD",
  welcome: "WELCOME",
  dashboard: "DASHBOARD",
  home: "HOME",
  transactions: "TRANSACTIONS",
  wallet: "WALLET",
  statistics: "STATISTICS",
  settings: "SETTINGS",
};
